import {environment} from './../../environments/environment'
export class ApiConfig {
    public static URL = environment.apiURL //'http://localhost:8000/'
    public static DISH = 'dish'
    public static DISHCATEGORY = 'dishCategory'
    public static CLIENT = 'admin'
    public static CLIENTCATEGORY = 'clientCategory'
    public static BANKDETAILS = 'bankDetails'
    public static ENDUSER = 'endUser'
    public static USER = 'user'
    public static CITY = 'StateCity/GetCity'
    public static STATE = 'StateCity/GetState'
    public static USERFEEDBACK = 'userFeedback'
    public static MASTERADMIN = 'masterAdmin'
}